name: 分析股票趋势

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 时间 00:00 运行
  workflow_dispatch:  # 允许手动触发

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置 Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install backtesting

      - name: 创建必要的目录结构
        run: |
          mkdir -p data/analysis
          mkdir -p data/json
          mkdir -p reports

      - name: 准备数据文件
        run: |
          # 创建空的分析文件，如果流程失败可以继续执行后续步骤
          touch data/analysis/nasdaq100_analysis.csv
          touch data/analysis/hstech50_analysis.csv
          
          # 创建基本的JSON文件结构
          echo '{"symbols": []}' > data/json/nasdaq100_symbols.json
          echo '{"symbols": []}' > data/json/hstech50_symbols.json

      - name: 生成分析报表
        run: |
          # 使用run_strategy.py生成报表
          python run_strategy.py --strategy index_analysis --index all --auto_report

      - name: 配置邮件发送环境
        env:
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          EMAIL_RECIPIENTS: ${{ secrets.EMAIL_RECIPIENTS }}
        run: |
          # 创建.env文件
          echo "EMAIL_SENDER=$EMAIL_SENDER" > .env
          echo "EMAIL_PASSWORD=$EMAIL_PASSWORD" >> .env
          echo "SMTP_SERVER=$SMTP_SERVER" >> .env
          echo "SMTP_PORT=$SMTP_PORT" >> .env
          echo "EMAIL_RECIPIENTS=$EMAIL_RECIPIENTS" >> .env

      - name: 发送分析报表邮件
        run: |
          # 使用run_strategy.py发送邮件
          python run_strategy.py --strategy index_analysis --index all --send_email

      - name: 提交分析结果
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data/analysis/nasdaq100_analysis.csv data/analysis/hstech50_analysis.csv
          git add data/json/nasdaq100_symbols.json data/json/hstech50_symbols.json
          git add reports/nasdaq100_analysis_*.html reports/hstech50_analysis_*.html
          git commit -m "更新股票分析结果 $(date +'%Y-%m-%d')" || echo "没有变更需要提交"
          git push
