name: 每日检测上涨大趋势股票

on:
  schedule:
    # 每天早上8点运行（UTC时间，对应北京时间16点）
    - cron: '0 8 * * *'
  workflow_dispatch:  # 允许手动触发

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        
      - name: 设置Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install tqdm beautifulsoup4 requests
          
      - name: 创建数据目录
        run: |
          mkdir -p data/csv data/html data/json
          
      - name: 获取纳斯达克前100股票
        run: python scripts/analysis/get_nasdaq_top100.py
        
      - name: 检测上涨大趋势股票
        run: python scripts/analysis/batch_analyze_stocks.py --uptrend_only --output data/csv/nasdaq100_uptrend_$(date +'%Y-%m-%d').csv
          
      - name: 提交分析结果到仓库
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          
          # 确保json文件存在
          if [ -f "data/json/nasdaq100_symbols.json" ]; then
            git add data/json/nasdaq100_symbols.json
          fi
          
          # 获取今天的日期
          TODAY=$(date +'%Y-%m-%d')
          CSV_FILE="data/csv/nasdaq100_uptrend_${TODAY}.csv"
          
          # 确保csv文件存在
          if [ -f "$CSV_FILE" ]; then
            git add "$CSV_FILE"
          else
            # 如果分析结果为空，创建一个空文件
            echo "日期,股票代码,股票名称,当前价格,买入信号,卖出信号,收益率,上涨趋势,备注" > "$CSV_FILE"
            echo "${TODAY},N/A,N/A,0,No,No,0,No,当前没有处于上涨大趋势的股票" >> "$CSV_FILE"
            git add "$CSV_FILE"
          fi
          
          git commit -m "更新上涨大趋势股票分析结果 ${TODAY}" || echo "没有变更需要提交"
          git push || echo "推送失败，可能是权限问题"
