name: 分析纳斯达克前100股票

on:
  schedule:
    # 每周一早上8点运行（UTC时间，对应北京时间周一16点）
    - cron: '0 8 * * 1'
  workflow_dispatch:  # 允许手动触发

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3
        
      - name: 设置Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install tqdm beautifulsoup4 requests
          
      - name: 创建数据目录
        run: |
          mkdir -p data/csv data/html data/json
          
      - name: 获取纳斯达克前100股票
        run: python scripts/analysis/get_nasdaq_top100.py
        
      - name: 分析股票
        run: python scripts/analysis/batch_analyze_stocks.py --signal_only --output data/csv/nasdaq100_analysis.csv
        
      - name: 保存分析结果
        uses: actions/upload-artifact@v3
        with:
          name: analysis-results
          path: data/csv/nasdaq100_analysis.csv
          
      - name: 提交分析结果到仓库
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add data/csv/nasdaq100_analysis.csv data/json/nasdaq100_symbols.json
          git commit -m "更新股票分析结果 $(date +'%Y-%m-%d')" || echo "没有变更需要提交"
          git push || echo "推送失败，可能是权限问题"
